### ISSUE TITLE
Failed to load the valhalla package

### ISSUE THREAD

**Issue by PDDStudio** [Bat41/valhalla#31]
[Enter steps to reproduce:]

1. Update valhalla to the latest version
2. Start Atom (can confirm crashing on v1.14.3 and v1.14.4)
**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [valhalla](https://github.com/Bat41/valhalla) package 1.0.2

### Stack Trace

Failed to load the valhalla package

```
At Cannot read property 'toString' of null

TypeError: Cannot read property 'toString' of null
    at /packages/valhalla/lib/valhalla.js:57:28
    at /packages/valhalla/lib/valhalla.js:58:6)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:794:28
```

### Commands

```
```

### Non-Core Packages

```
api-workbench 0.8.43 
atom-ternjs 0.17.2 
autocomplete-modules 1.6.7 
clipboard-ide 0.7.0 
css-color-underline 1.0.1 
editorconfig 2.2.2 
es6-javascript 1.0.0 
format-shell 2.0.0 
javascript-snippets 1.2.1 
json-colorer 1.0.0 
language-babel 2.55.6 
language-unix-shell 0.40.1 
language-vala-modern 0.3.2 
linter 1.11.23 
linter-eslint 8.1.2 
linter-shellcheck 1.4.3 
minimap-pigments 0.2.2 
nord-atom-syntax 0.6.0 
nord-atom-ui 0.10.1 
nuclide 0.208.0 
pigments 0.39.0 
process-palette 0.12.0 
project-plus 0.9.0 
selly-syntax-ide 2.0.2 
selly-ui-ide 3.1.0 
TerminalColor 1.1.0 
tool-bar 1.0.1 
tool-bar-main 0.0.10 
valhalla 1.0.2 
```

**Comment by Bat41** [comment]
What is the output and the return code of `pkg-config --modversion glib-2.0`, please ?

**Comment by PDDStudio** [comment]
@Bat41 Thanks for your fast reply.

```bash
> pkg-config --modversion glib-2.0
2.50.3
```

**Comment by PDDStudio** [comment]
In addition, this error occurs as well:

```
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [valhalla](https://github.com/Bat41/valhalla) package 1.0.2


### Stack Trace

Failed to activate the valhalla package

At Cannot read property 'split' of undefined

TypeError: Cannot read property 'split' of undefined
    at Object.activate (/packages/valhalla/lib/valhalla.js:166:28)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28

### Commands

### Non-Core Packages

api-workbench 0.8.43 
atom-ternjs 0.17.2 
autocomplete-modules 1.6.7 
builder 0.0.1 
clipboard-ide 0.7.0 
css-color-underline 1.0.1 
editorconfig 2.2.2 
es6-javascript 1.0.0 
format-shell 2.0.0 
javascript-snippets 1.2.1 
json-colorer 1.0.0 
language-babel 2.55.6 
language-unix-shell 0.40.1 
language-vala-modern 0.3.2 
linter 1.11.23 
linter-eslint 8.1.2 
linter-shellcheck 1.4.3 
minimap-pigments 0.2.2 
nord-atom-syntax 0.6.0 
nord-atom-ui 0.10.1 
nuclide 0.208.0 
pigments 0.39.0 
process-palette 0.12.0 
project-plus 0.9.0 
selly-syntax-ide 2.0.2 
selly-ui-ide 3.1.0 
TerminalColor 1.1.0 
tool-bar 1.0.1 
tool-bar-main 0.0.10 
valhalla 1.0.2 
```

**Comment by Bat41** [comment]
OK thanks. I just published v1.0.3 with a patch for your problem. Tell me if it works now. :)

**Comment by PDDStudio** [comment]
@Bat41 This was fast, thanks! The first issue seems to be gone now, but the second one is still present (the one I posted just at the same time you replied)

**Comment by Bat41** [comment]
Ah yes, I'm stupid, I don't provide a default vapi location for Mac OS X. Do you know where are the .vapi files located on Mac OS X?

**Comment by PDDStudio** [comment]
@Bat41 It seems like this depends on the way _how_ vala(c) and all additional libraries are installed.

The most common one would be via homebrew.
In this case the *.vapi files are located in `/usr/local/Cellar/vala/0.34.4/share/vala-0.34/vapi/` where `0.34.4` might varray depending on the installed version (so a wildcard would be recommended - if possible)

Another option would probably be to start searching for `*.vapi` files from within `/usr/local/Cellar/vala/` as because any version is going to be installed here.

**Comment by Bat41** [comment]
I just published a patch. It's a bit dirty (hardcoded path 😁), but it's configurable and I'll fix it when I'll have some time.

**Comment by PDDStudio** [comment]
@Bat41 Thanks for this quick fix! :+1:  As of now there are no errors anymore and Atom is starting fine.

**Comment by Bat41** [comment]
Great! Let me know if you encounter any other issue or if you have any suggestion. 🙂
